config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :words, only: [:index]
  end
  resources :contacts
  resources :sessions, only: [:create]
  resources :relationships
  resources :categories
  resources :words
  resources :lessons do
    resources :answers
  end

  namespace :admin do
    resources :users
    resources :contacts
    resources :categories do
      resources :words
    end
  end
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  has_many :choices, dependent: :destroy
  has_many :lessons, through: :answer
  belongs_to :category

  validates :content, presence: true
  validate :check_box # カスタムバリデータ

  # モデル同士が関連付けられている時、ネストさせることで一度にまとめてレコードの更新ができるようにする。
  accepts_nested_attributes_for :choices

  # 3択問題で、選んだ回答が正しいかcorrect: trueで判定する
  def correct_choice
    choices.find_by(correct: true)
  end

  private

  # 3択問題で、正しい答えは1つにしかできないようにするメソッド
  def check_box
    correct_answer = choices.collect { |c| c.correct || nil }
    errors.add(:choices, 'checkbox should be 1 !') if correct_answer.compact.size != 1
  end
end

app/controllers/admin/words_controller.rb
# frozen_string_literal: true

# 管理者専用なのでモジュール化
module Admin
  class WordsController < AdminController
    def index
      @words = Word.where(category_id: params[:category_id])
    end

    def new
      category = Category.find(params[:category_id])
      @word = category.words.build
      3.times do # 3回繰り返す
        @word.choices.build
      end
    end

    def create
      category = Category.find(params[:category_id])
      @word = category.words.build(word_params)
      if @word.save
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def show
      @word = Word.find(params[:id])
    end

    def edit
      @word = Word.find(params[:id])
    end

    def update
      @word = Word.find(params[:id])
      if @word.update_attributes(word_params)
        redirect_to admin_categories_path
      else
        render :edit
      end
    end

    def destroy
      @word = Word.find(params[:id]).destroy
      redirect_to admin_categories_path
    end

    private

    def word_params
      params.require(:word).permit(:content, choices_attributes: %i[id content correct])
    end
  end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  before_action :require_login
  
  def index
    @user = User.find(params[:user_id])
    @answers = @user.answers
  end
end

app/helpers/words_helper.rb
# frozen_string_literal: true

module WordsHelper
end

app/views/admin/words/edit.html.erb
<div class="container pt-5">
  <div class="row">
    <div class= "col-lg-6 offset-3 mx-auto">
      <h1 class="text-center m-5">Edit Words</h1>
      <hr />
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-body">
            <%= form_for ([:admin, :category, @word]) do |f|%>
              <%= render "shared/error_messages", object: f.object %>
              <div class="form-group">
                <%= f.label :content, "Words" %>
                <%= f.text_field :content, class: "form-control" %>
              </div>
              <%= f.fields_for :choices do |c|%>
                <%= render "shared/error_messages", object: c.object %>
                <div class="form-group form-inline mr-2">
                  <%= c.label :content, "Choices" %>
                  <%= c.text_field :content, class: " ml-2 mr-2" %><br />
                  <%= c.check_box :correct, calss: " ml-2 mr-2" %>
                </div>
              <% end %>
              <div class="text-center">
                <%= f.submit "Edit", class: "btn btn-primary" %>
                <%= link_to "Back", admin_category_words_path, class: "btn btn-link" %>
              </div>
            <% end %>
          </div>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-10 offset-1 mx-auto mt-5">
      <div class="card">
        <div class="card-header float-center">
          <h3>Admin | Words</h3>
          <%= link_to "Add word",new_admin_category_word_path, class: "btn btn-info" %>
        </div>
        <div class="card-body">
          <table class="table table-striped table-bordered text-center">
            <thead>
              <tr>
                <th><h6>Words</h6></th>
                <th><h6>Answer</h6></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @words.each do |word| %>
                <tr>
                  <td><%= word.content %></td>
                  <td><%= word.choices.find_by(correct: true).content %></td>
                  <td>
                    <%= link_to 'Edit', edit_admin_category_word_path(id: word), class: "mr-2"%>
                    <%= link_to 'Delete', admin_category_word_path(id: word), method: :delete, data: { confirm: 'You sure?' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<div class="container pt-5">
  <div class="row">
    <div class= "col-lg-6 offset-3 mx-auto">
      <h1 class="text-center m-5">Create Words</h1>
      <hr />
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-body">
            <%= form_for ([:admin, :category, @word]) do |f|%>
              <%= render "shared/error_messages", object: f.object %>
              <div class="form-group">
                <%= f.label :content, "Words" %>
                <%= f.text_field :content, class: "form-control" %>
              </div>
              <%= f.fields_for :choices do |c|%>
                <%= render "shared/error_messages", object: c.object %>
                <div class="form-group form-inline mr-2">
                  <%= c.label :content, "Choices" %>
                  <%= c.text_field :content, class: " ml-2 mr-2" %><br />
                  <%= c.check_box :correct, class: " ml-2 mr-2" %>
                </div>
              <% end %>
              <div class="text-center">
                <%= f.submit "Register", class: "btn btn-primary" %>
                <%= link_to "Back", admin_category_words_path, class: "btn btn-link" %>
              </div>
            <% end %>
          </div>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>