config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :words, only: [:index]
  end
  resources :contacts
  resources :sessions, only: [:create]
  resources :relationships
  resources :categories
  resources :words
  resources :lessons do
    resources :answers
  end

  namespace :admin do
    resources :users
    resources :contacts
    resources :categories do
      resources :words
    end
  end
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  belongs_to :action, polymorphic: true # ポリモーフィック関連の設定。
  belongs_to :user
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :choice
  belongs_to :word
  belongs_to :lesson
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/models/choice.rb
# frozen_string_literal: true

class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy

  validates :content, presence: true
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers

  belongs_to :category
  belongs_to :user
  has_one :activity, as: :action, dependent: :destroy

  # DBから次の問題（単語）を表示するためのメソッド
  def next_word
    (category.words - words).first
  end

  # 3択問題のうち正しい回答にするメソッド
  def correct_choice
    choices.where(correct: true)
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  # アソシエーションの定義。activityではなくactionという名前で働く。
  has_one :activity, as: :action, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :lessons, dependent: :destroy
  has_many :answers, through: :lessons
  has_many :activities, dependent: :destroy
  # class_nameで1つのモデルに対して、二つのアソシエーションを組む。
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # 中間テーブルがあるのでsourceオプションを使用。
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :nickname, presence: true, length: { maximum: 10, minimum: 3 }
  validates :realname, presence: true
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_nil: true

  # フォローするメソッド
  def follow(other_user)
    following << other_user
  end

  # アンフォローのメソッド
  def unfollow(other_user)
    following.delete(other_user)
  end

  #フォローしているか調べるメソッド
  def following?(other_user)
    following.include?(other_user)
  end

  # フォロー/アンフォローのアクティビィティを検索するメソッド
  def feed
    following_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
    Activity.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  has_many :choices, dependent: :destroy
  has_many :lessons, through: :answer
  belongs_to :category

  validates :content, presence: true
  validate :check_box # カスタムバリデータ

  # モデル同士が関連付けられている時、ネストさせることで一度にまとめてレコードの更新ができるようにする。
  accepts_nested_attributes_for :choices

  # 3択問題で、選んだ回答が正しいかcorrect: trueで判定する
  def correct_choice
    choices.find_by(correct: true)
  end

  private

  # 3択問題で、正しい答えは1つにしかできないようにするメソッド
  def check_box
    correct_answer = choices.collect { |c| c.correct || nil }
    errors.add(:choices, 'checkbox should be 1 !') if correct_answer.compact.size != 1
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :require_login
  before_action :require_admin # ログインしているユーザーが管理者かどうか判定

  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/activities_helper.rb
# frozen_string_literal: true

module ActivitiesHelper
  def rel_activity(id)
    Relationship.find(id).followed
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/lessons_helper.rb
# frozen_string_literal: true

module LessonsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def login(user) # sessionを使用したログイン用メソッド
    session[:user_id] = user.id
  end

  def current_user # sessionを使用した現在ログイン済ユーザーメソッド
    User.find_by(id: session[:user_id])
  end

  def logged_in? # 現在ユーザーがログインしているか存在しているか判定するメソッド
    !current_user.nil?
  end

  def logout #sessionを使用したログアウト用メソッド
    session.delete(:user_id)
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # ユーザーのプロフィール写真に「Gravatar」を使用できるようにする。
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    image_size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url)
  end

  def user_act(id)
    User.find(id)
  end
end

app/helpers/words_helper.rb
# frozen_string_literal: true

module WordsHelper
end

app/views/admin/index.html.erb
<br />
<br />
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-10 offset-1 mx-auto">
      <div class="card user-list">
        <div class="card-header">
          <h3>Users List</h3><hr />
        </div>
        <div class="card-body">
          <table class="table table-striped table-bordered　table-responsive">
            <thead>
              <tr>
                <th><h6>Image</h6></th>
                <th><h6>Nickname</h6></th>
                <th><h6>Realname</h6></th>
                <th><h6>E-mail</h6></th>
                <th><h6>Admin</h6></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td aria-labe><%= link_to gravatar_for(user) %></td>
                  <td aria-labe><%= user.nickname %></td>
                  <td aria-labe><%= user.realname %></td>
                  <td aria-labe><%= user.email %></td>
                  <td aria-labe>
                    <% if user.admin?%>
                      <%= link_to "Remove as Admin", admin_user_path(id: user), method: :put, class: "btn btn-danger"%>
                    <% else %>
                      <%= link_to "Set as Admin", admin_user_path(id: user), method: :put, class: "btn btn-primary"%>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning pt-5">
    <ul>
      <% object.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="p-3">
  <div class="container text-center">
    <small>Allrightreserved &copy; Yoshiro Kato</small>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <%=link_to "E-learning System", root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end mr-5" id="navbarNavDropdown">
    <% if logged_in? %>
      <div class="navbar-nav active">
        <%= link_to "Dashboard", root_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav active">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav active">
        <%= link_to "Categories", categories_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav active mr-5">
        <% if current_user.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.realname %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", current_user, class: "dropdown-item"%><br />
              <%= link_to "User Management", admin_users_path, class: "dropdown-item" %><br />
              <%= link_to "Setting Categories", admin_categories_path, class: "dropdown-item" %><br />
            </div>
          </li>
        <% end %>
      </div>
      <div class="navbar-nav m-2">
        <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-outline-warning" %>
      </div>
    <% else %>
      <div class="navbar-nav m-2">
        <%= link_to "Login", login_path, class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</nav>