config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :words, only: [:index]
  end
  resources :contacts
  resources :sessions, only: [:create]
  resources :relationships
  resources :categories
  resources :words
  resources :lessons do
    resources :answers
  end

  namespace :admin do
    resources :users
    resources :contacts
    resources :categories do
      resources :words
    end
  end
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  belongs_to :action, polymorphic: true # ポリモーフィック関連の設定。
  belongs_to :user
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :choice
  belongs_to :word
  belongs_to :lesson
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/models/choice.rb
# frozen_string_literal: true

class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy

  validates :content, presence: true
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers

  belongs_to :category
  belongs_to :user
  has_one :activity, as: :action, dependent: :destroy

  # DBから次の問題（単語）を表示するためのメソッド
  def next_word
    (category.words - words).first
  end

  # 3択問題のうち正しい回答にするメソッド
  def correct_choice
    choices.where(correct: true)
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  # アソシエーションの定義。activityではなくactionという名前で働く。
  has_one :activity, as: :action, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :lessons, dependent: :destroy
  has_many :answers, through: :lessons
  has_many :activities, dependent: :destroy
  # class_nameで1つのモデルに対して、二つのアソシエーションを組む。
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # 中間テーブルがあるのでsourceオプションを使用。
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :nickname, presence: true, length: { maximum: 10, minimum: 3 }
  validates :realname, presence: true
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_nil: true

  # フォローするメソッド
  def follow(other_user)
    following << other_user
  end

  # アンフォローのメソッド
  def unfollow(other_user)
    following.delete(other_user)
  end

  #フォローしているか調べるメソッド
  def following?(other_user)
    following.include?(other_user)
  end

  # フォロー/アンフォローのアクティビィティを検索するメソッド
  def feed
    following_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
    Activity.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  has_many :choices, dependent: :destroy
  has_many :lessons, through: :answer
  belongs_to :category

  validates :content, presence: true
  validate :check_box # カスタムバリデータ

  # モデル同士が関連付けられている時、ネストさせることで一度にまとめてレコードの更新ができるようにする。
  accepts_nested_attributes_for :choices

  # 3択問題で、選んだ回答が正しいかcorrect: trueで判定する
  def correct_choice
    choices.find_by(correct: true)
  end

  private

  # 3択問題で、正しい答えは1つにしかできないようにするメソッド
  def check_box
    correct_answer = choices.collect { |c| c.correct || nil }
    errors.add(:choices, 'checkbox should be 1 !') if correct_answer.compact.size != 1
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# 管理者専用なのでモジュール化
module Admin
  class UsersController < AdminController
    def index
      @users = User.all
    end

    def update
      @user = User.find(params[:id])
      if @user.admin? # ユーザーが管理者かチェック
        @user.update(admin: false)
      else
        @user.update(admin: true)
      end
      redirect_to admin_users_url
    end
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :require_login
  before_action :require_admin # ログインしているユーザーが管理者かどうか判定

  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :correct_user, only: %i[edit update]
  before_action :require_login, except: %i[signup create]
  before_action :require_admin, only: [:destroy]

  def signup
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render :signup
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to current_user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :realname, :email, :password, :password_confirmation)
  end

  def correct_user # 現在ログインしているユーザーと更新したいユーザー情報が一致しているか
    @user = User.find(params[:id])
    redirect_to root_url unless @user == current_user
  end

  def require_admin # ユーザーに対し管理者か判定するメソッド
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  before_action :require_login
  
  def index
    @user = User.find(params[:user_id])
    @answers = @user.answers
  end
end

app/helpers/activities_helper.rb
# frozen_string_literal: true

module ActivitiesHelper
  def rel_activity(id)
    Relationship.find(id).followed
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

# 管理者専用なのでモジュール化
module Admin
  module UsersHelper
    # ユーザーのプロフィール写真に「Gravatar」を使用できるようにする。
    def gravatar_for(user, options = { size: 80 })
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      image_size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url)
    end
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/lessons_helper.rb
# frozen_string_literal: true

module LessonsHelper
end

app/helpers/relationships_helper.rb
# frozen_string_literal: true

module RelationshipsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def login(user) # sessionを使用したログイン用メソッド
    session[:user_id] = user.id
  end

  def current_user # sessionを使用した現在ログイン済ユーザーメソッド
    User.find_by(id: session[:user_id])
  end

  def logged_in? # 現在ユーザーがログインしているか存在しているか判定するメソッド
    !current_user.nil?
  end

  def logout #sessionを使用したログアウト用メソッド
    session.delete(:user_id)
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # ユーザーのプロフィール写真に「Gravatar」を使用できるようにする。
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    image_size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url)
  end

  def user_act(id)
    User.find(id)
  end
end

app/helpers/words_helper.rb
# frozen_string_literal: true

module WordsHelper
end

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build do |f| %>
  <%= hidden_field_tag :followed_id, user.id %>
  <%= f.submit "follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class= "form-group">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: "form-control" %>
  </div>
  <div class= "form-group">
    <%= f.label :realname %>
    <%= f.text_field :realname, class: "form-control" %>
  </div>
  <div class= "form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit btn_msg, class: "btn #{btn_type} btn-block" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: user.id), html: {method: :delete } do |f| %>
  <%= f.submit "unfollow", class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-6 offset-3 mx-auto">
      <h1 class="text-center m-5">Edit</h1>
      <hr />
      <%= render "form", btn_msg: "Update",btn_type: "btn-success" %>
    </div>
  </div>
</div>

app/views/users/home_feed.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-3 mt-5">
      <div class="card mb-3">
        <div class="card-body text-center float-left">
          <h4 class="p-1">Dashboard</h4>
          <%= gravatar_for current_user %>
          <h3 class="p-1"><%= current_user.nickname %></h3>
          <%= current_user.email %><br />
          <%= link_to "Learned words", user_words_path(current_user), class: "m-auto"%><br />
        </div>
      </div>
    </div>
    <div class="col-lg-9 pt-5">
      <div class="card">
        <div class="card-header">
          <h4 class="pl-1">Activities</h4>
          <hr />
          <% if !@activities.nil? %>
            <% @activities.each do |activity| %>
              <% if activity.action_type == "Lesson"%>
                <div class="media p-2">
                  <%= link_to gravatar_for activity.user, size: 100%>
                  <div class="media-body p-2">
                    <h4 class="ml-2"><%= activity.action.user.nickname %>は<%=activity.action.category.title %>を<%= activity.action.category.words.count %>問取り組みました。</h4>
                  </div>
                </div>
              <% else %>
                <div class="media p-2">
                  <%= link_to gravatar_for activity.user, size: 100 %>
                  <div class="media-body p-auto m-auto">
                    <h4 class="ml-2"><%= activity.user.nickname %>は<%=link_to user_act(activity.action.followed_id).nickname, user_path(user_act(activity.action.followed_id).id) %>をフォローしました。</h4>
                  </div>
                </div>
              <% end %>
              <hr />
            <% end %>
          <% else %>
            <h4 class="text-center">まだ何も行っていません。</h4>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<br />
<br />
<h1 class="text-center pt-5">Users List</h1>
<div class="container">
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-lg-9 offset-3 mx-auto">
        <div class="media p-2">
          <div class="align-self-center border mr-3">
            <%= link_to gravatar_for(user), user%>
          </div>
          <div class="media-body p-2">
            <h3><%= link_to user.nickname, user %></h3>
          </div>
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= render "unfollow", user: user %>
            <% else %>
              <%= render "follow", user: user %>
            <% end %>
          <% end %>
          <hr />
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="paginate text-center pt-3">
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-3 mt-5">
      <div class="card mb-3">
        <div class="card-body text-center float-left">
          <%= link_to gravatar_for @user, size: 400%>
            <h3><%= @user.nickname%></h3>
            <hr />
            <div class="row">
              <div class="col">
                <h3><%= @user.following.count %></h3>
                <small>Following</small><br />
                <h3><%= @user.followers.count %></h3>
                <small>Followers</small><br />
              </div>
            </div>
            <div class="col text-center btn-sm">
              <% unless current_user == @user %>
                <% if current_user.following?(@user) %>
                  <%= render "unfollow", user: @user %>
                <% else %>
                  <%= render "follow", user: @user %>
                <% end %>
              <% end %>
            </div>
            <%= link_to "Learned words", user_words_path(current_user), class: "border-bottom"%><br />
            <% if current_user == @user %>
              <%= link_to "Edit", edit_user_path(current_user), class: "btn btn-outline-primary float-center btn-sm"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-lg-9 pt-5">
        <div class="card">
          <div class="card-header">
            <h4 class="pl-1">Activities</h4>
            <hr />
            <% if !@activities.blank? %>
              <% @activities.each do |activity| %>
                <div class="media p-3">
                  <%= link_to gravatar_for @user, size: 100%>
                  <div class="media-body p-2">
                    <% if activity.action_type == "Lesson"%>
                      <h4 class="ml-2"><%= activity.action.user.nickname %>は<%=activity.action.category.title %>を<%= activity.action.category.words.count %>問取り組みました。</h4>
                    <% else %>
                      <h4 class="ml-2"><%= @user.nickname%>は<%= rel_activity(activity.action_id).nickname%>をフォローしました。</h4>
                    <% end %>
                  </div>
                </div>
                <hr />
              <% end %>
            <% else %>
              <h4 class="text-center">まだ何も行っていません。</h4>
            <% end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<div class="jumbotron text-center text-light" id="signup-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <h1 class="signup-title">Let's begin!</h1>
      </div>
      <div class="col-lg-4 col-lg-push-1">
        <h1 class="text-center m-5">Signup</h1>
        <hr />
        <%= render "form", btn_msg: "Signup",btn_type: "btn-success mb-5" %>
      </div>
    </div>
  </div>
</div>