config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :words, only: [:index]
  end
  resources :contacts
  resources :sessions, only: [:create]
  resources :relationships
  resources :categories
  resources :words
  resources :lessons do
    resources :answers
  end

  namespace :admin do
    resources :users
    resources :contacts
    resources :categories do
      resources :words
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

# 管理者専用なのでモジュール化
module Admin
  class CategoriesController < AdminController
    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update_attributes(category_params)
        redirect_to admin_categories_path
      else
        render :edit
      end
    end

    def destroy
      @category = Category.find(params[:id]).destroy
      redirect_to admin_categories_url
    end

    private

    def category_params
      params.require(:category).permit(:title, :description)
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :require_login
  
  def index
    @categories = Category.all
    @lesson = Lesson.new
  end

  def new; end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container pt-5">
  <div class="row">
    <div class= "col-lg-6 offset-3 mx-auto">
      <h1 class="text-center m-5"> Edit Category</h1>
      <hr />
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-body">
            <%= form_for([:admin, @category]) do |f|%>
              <%= render "shared/error_messages", object: f.object %>
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control" %>
              </div>
              <div class="text-center">
                <%= f.submit "Update" , class: "btn btn-success" %>
                <%= link_to "Back", admin_categories_path, class: "btn btn-link" %>
              </div>
            <% end %>
          </div>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-lg-10 offset-1 mx-auto mt-5">
      <div class="card">
        <div class="card-header float-center">
          <h3>Admin | Categories</h3>
          <%= link_to "Add category", new_admin_category_path, class: "btn btn-info" %>
        </div>
        <div class="card-body">
          <table class="table table-striped table-bordered text-center">
            <thead>
              <tr>
                <th><h6>Title</h6></th>
                <th><h6>Description</h6></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.title %></td>
                  <td><%= category.description %></td>
                  <td>
                    <%= link_to 'Show words',admin_category_words_path(category), class: "mr-2"%>
                    <%= link_to 'Add word', new_admin_category_word_path(category), class: "mr-2"%>
                    <%= link_to 'Edit', edit_admin_category_path(category), class: "mr-2"%>
                    <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: 'You sure?' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container pt-5">
  <div class="row">
    <div class= "col-lg-6 offset-3 mx-auto">
      <h1 class="text-center m-5">Category Registration</h1>
      <hr />
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-body">
            <%= form_for :category, url: admin_categories_path do |f|%>
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control" %>
              </div>
              <div class="text-center">
                <%= f.submit "Register", class: "btn btn-success" %>
                <%= link_to "Back", admin_categories_path, class: "btn btn-link" %>
              </div>
            <% end %>
          </div>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>